---
- hosts: localhost
  become: yes
  gather_facts: no
  vars_files:
    - /home/ndao/mysql_setup/vars/mysql_vars.yml
  vars_prompt:
    - name: mysql_root_password
      prompt: "Enter MySQL root password"
      private: yes
      
  tasks:
    - name: Loop through databases and users
      include_tasks: sql_setup.yml
      loop: "{{ databases }}"
      loop_control:
        loop_var: db_item
